=== epam/Wilma/wilma-application/modules/wilma-stub-configuration-parser/src/main/resources/StubConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://epam.github.io/Wilma/xsd/StubConfig"
           xmlns="http://epam.github.io/Wilma/xsd/StubConfig"
           targetNamespace="http://epam.github.io/Wilma/xsd/StubConfig" elementFormDefault="qualified">
    <xs:element name="wilma-stub" type="WilmaStubType">
        <xs:keyref name="templateFormatterSetRef" refer="templateFormatterSets">
            <xs:selector xpath=".//tns:template-formatter-set-invoker"/>
            <xs:field xpath="@name"/>
        </xs:keyref>
        <xs:key name="templateFormatterSets">
            <xs:selector xpath="./tns:template-descriptor/tns:template-formatter-set"/>
            <xs:field xpath="@name"/>
        </xs:key>
        <xs:keyref name="conditionSetRef" refer="conditionSets">
            <xs:selector xpath=".//tns:condition-set-invoker"/>
            <xs:field xpath="@name"/>
        </xs:keyref>
        <xs:key name="conditionSets">
            <xs:selector xpath="./tns:condition-templates/tns:condition-set"/>
            <xs:field xpath="@name"/>
        </xs:key>
        <xs:keyref name="templateRef" refer="templates">
            <xs:selector xpath="./tns:dialog-descriptor/tns:response-descriptor"/>
            <xs:field xpath="@template"/>
        </xs:keyref>
        <xs:keyref name="dialogDescriptorRef" refer="uniqueDialogDescriptor">
            <xs:selector xpath="./tns:sequence-descriptor/tns:dialog-descriptors/tns:dialog-descriptor-ref"/>
            <xs:field xpath="@ref"/>
        </xs:keyref>
        <xs:keyref name="sequenceDescriptorRef" refer="uniqueSequenceDescriptor">
            <xs:selector xpath="./tns:dialog-descriptor/tns:response-descriptor"/>
            <xs:field xpath="@sequenceDescriptorName"/>
        </xs:keyref>
        <xs:key name="templates">
            <xs:selector xpath="./tns:template-descriptor/tns:template"/>
            <xs:field xpath="@name"/>
        </xs:key>
        <xs:unique name="uniqueDialogDescriptor">
            <xs:selector xpath="tns:dialog-descriptor"/>
            <xs:field xpath="@name"/>
        </xs:unique>
        <xs:unique name="uniqueTemplateDescriptor">
            <xs:selector xpath="tns:template-descriptor"/>
            <xs:field xpath="@name"/>
        </xs:unique>
        <xs:unique name="uniqueConditionTemplates">
            <xs:selector xpath="tns:condition-templates"/>
            <xs:field xpath="@name"/>
        </xs:unique>
        <xs:unique name="uniqueSequenceDescriptor">
            <xs:selector xpath="tns:sequence-descriptor"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="WilmaStubType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="sequence-descriptor" type="SequenceDescriptor" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="dialog-descriptor" type="DialogDescriptor" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="template-descriptor" type="TemplateDescriptor" minOccurs="1" maxOccurs="unbounded">
                <xs:unique name="uniqueTemplate">
                    <xs:selector xpath="tns:template"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
                <xs:unique name="uniqueTemplateFormatterSet">
                    <xs:selector xpath="tns:template-formatter-set"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
            <xs:element name="condition-templates" type="ConditionTemplates" minOccurs="0" maxOccurs="unbounded">
                <xs:unique name="uniqueConditionSet">
                    <xs:selector xpath="tns:condition-set"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
            <xs:element name="interceptors" type="Interceptors" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="groupname" default="Default">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[^/|^/;]+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="active" type="xs:boolean" default="true"/>
    </xs:complexType>

    <xs:complexType name="DialogDescriptor">
        <xs:sequence>
            <xs:element name="condition-descriptor" type="ConditionDescriptor"/>
            <xs:element name="response-descriptor" type="ResponseDescriptor"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="usage" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="always"/>
                    <xs:enumeration value="timeout"/>
                    <xs:enumeration value="hitcount"/>
                    <xs:enumeration value="disabled"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="validityValue">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="SequenceDescriptor">
        <xs:sequence>
            <xs:element name="condition-descriptor" type="ConditionDescriptor" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="dialog-descriptors" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="dialog-descriptor-ref" type="DialogDescriptorRef"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="sequence-class-parameters" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="param" type="StringParam" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[^/|^/;]+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="class" type="xs:string" use="required"/>
        <xs:attribute name="timeout" type="xs:long"/>
    </xs:complexType>

    <xs:complexType name="DialogDescriptorRef">
        <xs:attribute name="ref" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="ConditionDescriptor">
        <xs:choice>
            <xs:element name="and" type="and"/>
            <xs:element name="or" type="or"/>
            <xs:element name="not" type="not"/>
            <xs:element name="condition" type="Condition"/>
            <xs:element name="condition-set-invoker" type="ConditionSetInvoker"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="Condition">
        <xs:sequence>
            <xs:element name="param" type="StringParam" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="class" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="negate" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="StringParam">
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="value" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="and">
        <xs:choice minOccurs="2" maxOccurs="unbounded">
            <xs:element name="condition" type="Condition"/>
            <xs:element name="condition-set-invoker" type="ConditionSetInvoker"/>
            <xs:element name="and" type="and"/>
            <xs:element name="or" type="or"/>
            <xs:element name="not" type="not"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="or">
        <xs:choice minOccurs="2" maxOccurs="unbounded">
            <xs:element name="condition" type="Condition"/>
            <xs:element name="condition-set-invoker" type="ConditionSetInvoker"/>
            <xs:element name="and" type="and"/>
            <xs:element name="or" type="or"/>
            <xs:element name="not" type="not"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="not">
        <xs:choice>
            <xs:element name="condition" type="Condition"/>
            <xs:element name="condition-set-invoker" type="ConditionSetInvoker"/>
            <xs:element name="and" type="and"/>
            <xs:element name="or" type="or"/>
            <xs:element name="not" type="not"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="ConditionSetInvoker">
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="ConditionTemplates">
        <xs:sequence>
            <xs:element name="condition-set" type="ConditionSet" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ConditionSet">
        <xs:choice>
            <xs:element name="and" type="and"/>
            <xs:element name="or" type="or"/>
            <xs:element name="not" type="not"/>
            <xs:element name="condition" type="Condition"/>
            <xs:element name="condition-set-invoker" type="ConditionSetInvoker"/>
        </xs:choice>
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="ResponseDescriptor">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="template-formatter" type="TemplateFormatter"/>
            <xs:element name="template-formatter-set-invoker" type="TemplateFormatterSetInvoker"/>
        </xs:choice>
        <xs:attributeGroup ref="responseDescriptorAttributes"/>
    </xs:complexType>

    <xs:attributeGroup name="responseDescriptorAttributes">
        <xs:attribute name="delay" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="code" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <!-- to ask about other error codes -->
                    <xs:minInclusive value="100"/>
                    <xs:maxExclusive value="600"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="mimetype" use="required" type="xs:string"/>
        <xs:attribute name="template" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="sequenceDescriptorName">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>

    <xs:complexType name="TemplateDescriptor">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="template-formatter-set" type="TemplateFormatterSet"/>
            <xs:sequence minOccurs="1">
                <xs:element maxOccurs="unbounded" name="template" type="Template"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" name="template-formatter-set"
                            type="TemplateFormatterSet"/>
            </xs:sequence>
        </xs:sequence>

        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="Template">
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="xml"></xs:enumeration>
                    <xs:enumeration value="text"></xs:enumeration>
                    <xs:enumeration value="html"></xs:enumeration>
                    <xs:enumeration value="json"></xs:enumeration>
                    <xs:enumeration value="xmlfile"></xs:enumeration>
                    <xs:enumeration value="textfile"></xs:enumeration>
                    <xs:enumeration value="htmlfile"></xs:enumeration>
                    <xs:enumeration value="jsonfile"></xs:enumeration>
                    <xs:enumeration value="external"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="resource" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="TemplateFormatterSet">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="template-formatter" type="TemplateFormatter"/>
            <xs:element name="template-formatter-set-invoker" type="TemplateFormatterSetInvoker"/>
        </xs:choice>
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="TemplateFormatterSetInvoker">
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="TemplateFormatter">
        <xs:sequence>
            <xs:element name="param" type="AnySimpleTypeParam" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="class" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="Interceptors">
        <xs:sequence>
            <xs:element name="interceptor" type="Interceptor" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Interceptor">
        <xs:sequence>
            <xs:element name="param" type="AnySimpleTypeParam" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="class" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="AnySimpleTypeParam">
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="value" type="xs:anySimpleType" use="required"/>
    </xs:complexType>

</xs:schema>

=== epam/Wilma/wilma-functionaltest/resources/stubconfig/jar/stubConfigWithInterceptorJar.xml
<?xml version="1.0" encoding="UTF-8"?>
<wilma-stub xmlns="http://epam.github.io/Wilma/xsd/StubConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://epam.github.io/Wilma/xsd/StubConfig http://epam.github.io/Wilma/xsd/StubConfig.xsd">
  <dialog-descriptor name="dialog-descriptor" usage="always" comment="random comment">
    <condition-descriptor>
      <condition class="com.epam.sandbox" />
    </condition-descriptor>
    <response-descriptor code="404" delay="0" mimetype="xml" template="exampleTemplate1"/>
  </dialog-descriptor>
  <template-descriptor name="templateDescriptor1">
  <template name="exampleTemplate1" type="xml" resource="templateExample.xml"/>
  </template-descriptor>
  <interceptors>
  	<interceptor class="com.epam.sandbox" name="Request-Interceptor-Jared"/>
  	<interceptor class="com.epam.sandbox" name="Response-Interceptor-Jared"/>
  </interceptors>
</wilma-stub>

=== epam/Wilma/wilma-functionaltest/resources/sequence/stubConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<wilma-stub xmlns="http://epam.github.io/Wilma/xsd/StubConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://epam.github.io/Wilma/xsd/StubConfig http://epam.github.io/Wilma/xsd/StubConfig.xsd">
  
   <sequence-descriptor name="sequenceDescriptorName" class="com.epam.message.sequence.test.SingleSequenceHandler" timeout="120000">
        <condition-descriptor>
            <condition class="AlwaysTrueChecker" />
        </condition-descriptor>
    </sequence-descriptor>

  <dialog-descriptor name="super-descriptor" usage="always" comment="random comment">
    <condition-descriptor>
      <condition class="com.epam.message.sequence.test.SimpleBodyChecker">
      	<param name="text" value="d" />
      </condition>
    </condition-descriptor>
    <response-descriptor code="200" delay="0" mimetype="text/plain" template="notUsedResponse" sequenceDescriptorName="sequenceDescriptorName">
      <template-formatter class="com.epam.message.sequence.test.SequenceBodyTemplateFormatter"/>
    </response-descriptor>
  </dialog-descriptor>
  
  <dialog-descriptor name="super-descriptor2" usage="always" comment="random comment">
    <condition-descriptor>
      <condition class="AlwaysTrueChecker" />
    </condition-descriptor>
    <response-descriptor code="200" delay="0" mimetype="text/plain" template="welcomeResponse" />
  </dialog-descriptor>
  
  <template-descriptor name="template-descriptor_1">
    <template name="notUsedResponse" type="text" resource="Not used :)" />
    <template name="welcomeResponse" type="text" resource="welcome" />
  </template-descriptor>
</wilma-stub>

=== epam/Wilma/wilma-extras/circuit.breaker/src/main/resources/circuitBreakerStubConfigExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<wilma-stub xmlns="http://epam.github.io/Wilma/xsd/StubConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://epam.github.io/Wilma/xsd/StubConfig http://epam.github.io/Wilma/xsd/StubConfig.xsd">
    <dialog-descriptor name="CircuitBreakerExampleConfiguration" usage="always" comment="Circuit Breaker">
        <condition-descriptor>
            <condition class="com.epam.wilma.extras.circuit.breaker.CircuitBreakerChecker">
                <param name="path" value="http://"/>
                <param name="timeoutInSec" value="15"/>
                <param name="successCodes" value="200,201,303"/>
                <param name="maxErrorCount" value="4"/>
            </condition>
        </condition-descriptor>
        <response-descriptor code="503" delay="0" mimetype="text/plain" template="circuitBreakerTemplate">
            <template-formatter class="com.epam.wilma.extras.shortcircuit.ShortCircuitResponseGenerator"/>
        </response-descriptor>
    </dialog-descriptor>
    <template-descriptor name="templateDescriptor1">
        <template name="circuitBreakerTemplate" type="external"
                  resource="com.epam.wilma.extras.circuit.breaker.CircuitBreakerResponseGenerator"/>
    </template-descriptor>
    <interceptors>
        <interceptor name="Circuit Breaker Response Investigator"
                     class="com.epam.wilma.extras.shortcircuit.CircuitBreakerInterceptor"/>
    </interceptors>
</wilma-stub>

=== epam/Wilma/wilma-extras/forward.proxy/src/main/resources/forwardProxyStubConfigExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<wilma-stub xmlns="http://epam.github.io/Wilma/xsd/StubConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://epam.github.io/Wilma/xsd/StubConfig http://epam.github.io/Wilma/xsd/StubConfig.xsd" groupname="ForwardProxy">
    <dialog-descriptor name="ForwardProxyExampleConfiguration" usage="always" comment="Forward Proxy">
        <condition-descriptor>
                <condition class="AlwaysFalseChecker" />
        </condition-descriptor>
        <response-descriptor code="200" delay="0" mimetype="text/plain" template="forwardProxyTemplate">
        </response-descriptor>
    </dialog-descriptor>
    <template-descriptor name="templateDescriptor1">
        <template name="forwardProxyTemplate" type="text" resource="Dummy response."/>
    </template-descriptor>
    <interceptors>
        <interceptor name="Forward Proxy Interceptor" class="com.epam.wilma.extras.forwardproxy.ForwardProxyInterceptor" />
    </interceptors>
</wilma-stub>

=== epam/Wilma/wilma-functionaltest/resources/sequence/sequenceDialogDescriptorStubConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<wilma-stub xmlns="http://epam.github.io/Wilma/xsd/StubConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://epam.github.io/Wilma/xsd/StubConfig http://epam.github.io/Wilma/xsd/StubConfig.xsd">
  
   <sequence-descriptor name="default-sequenceDescriptorName" class="com.epam.message.sequence.test.SingleSequenceHandler" timeout="120000">
        <dialog-descriptors>
			<dialog-descriptor-ref ref="super-descriptor"/>      
        </dialog-descriptors>
    </sequence-descriptor>

  <dialog-descriptor name="super-descriptor" usage="always" comment="random comment">
    <condition-descriptor>
      <condition class="AlwaysTrueChecker"/>
    </condition-descriptor>
    <response-descriptor code="200" delay="0" mimetype="text/plain" template="notUsedResponse" sequenceDescriptorName="default-sequenceDescriptorName">
      <template-formatter class="com.epam.message.sequence.test.SequenceBodyTemplateFormatter"/>
    </response-descriptor>
  </dialog-descriptor>
  
  <template-descriptor name="template-descriptor_1">
    <template name="notUsedResponse" type="text" resource="Not used :)" />
  </template-descriptor>
</wilma-stub>

=== epam/Wilma/wilma-extras/reverse.proxy/src/main/resources/reverseProxyStubConfigExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<wilma-stub xmlns="http://epam.github.io/Wilma/xsd/StubConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://epam.github.io/Wilma/xsd/StubConfig http://epam.github.io/Wilma/xsd/StubConfig.xsd" groupname="ReverseProxy">
    <dialog-descriptor name="ReverseProxyExampleConfiguration" usage="always" comment="Reverse Proxy">
        <condition-descriptor>
                <condition class="AlwaysFalseChecker" />
        </condition-descriptor>
        <response-descriptor code="200" delay="0" mimetype="text/plain" template="reverseProxyTemplate">
        </response-descriptor>
    </dialog-descriptor>
    <template-descriptor name="templateDescriptor1">
        <template name="reverseProxyTemplate" type="text" resource="Dummy response."/>
    </template-descriptor>
    <interceptors>
        <interceptor name="Reverse Proxy Interceptor" class="com.epam.wilma.extras.reverseProxy.ReverseProxyInterceptor" />
    </interceptors>
</wilma-stub>

=== epam/Wilma/wilma-functionaltest/resources/stubconfig/responseformatter/stubConfigWithInvalidClassFormatTemplateFormatter.xml
<?xml version="1.0" encoding="UTF-8"?>
<wilma-stub xmlns="http://epam.github.io/Wilma/xsd/StubConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://epam.github.io/Wilma/xsd/StubConfig http://epam.github.io/Wilma/xsd/StubConfig.xsd">
  <dialog-descriptor name="dialog-descriptor" usage="always" comment="random comment">
    <condition-descriptor>
      <condition class="OrPatternChecker" />
    </condition-descriptor>
    <response-descriptor code="404" delay="0" mimetype="json" template="exampleTemplate1">
      <template-formatter class="XslBasedTemplateFormatter">
        <param name="param1" value="value1" />
        <param name="param2" value="value2" />
      </template-formatter>
      <template-formatter-set-invoker name="templateFormatterSet1"/>
    </response-descriptor>
  </dialog-descriptor>
  <template-descriptor name="templateDescriptor1">
  <template name="exampleTemplate1" type="xml" resource="something"/>
  <template-formatter-set name="templateFormatterSet1">
  <template-formatter class="InvalidClassFormatExternalTemplateFormatter"/>
  </template-formatter-set>
  </template-descriptor>
</wilma-stub>

=== epam/Wilma/wilma-extras/lookandsay.service/src/main/resources/LookAndSayServiceStubConfigExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<wilma-stub xmlns="http://epam.github.io/Wilma/xsd/StubConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://epam.github.io/Wilma/xsd/StubConfig http://epam.github.io/Wilma/xsd/StubConfig.xsd">
    <dialog-descriptor name="dialog-descriptor" usage="disabled" comment="Thi is just a dummy dialog descriptor, disabled by default.">
        <condition-descriptor>
            <condition class="OrUrlPatternChecker" >
                <param name="dummy" value="http://" />
            </condition>
        </condition-descriptor>
        <response-descriptor code="200" delay="0" mimetype="text/plain" template="dummyTemplate">
        </response-descriptor>
    </dialog-descriptor>
    <template-descriptor name="templateDescriptor1">
        <template name="dummyTemplate" type="text" resource="Look-And-Say service"/>
    </template-descriptor>
    <interceptors>
        <interceptor name="Look-And-Say Service" class="com.epam.wilma.extras.lookandsayservice.LookAndSayServiceInterceptor">
        </interceptor>
    </interceptors>
</wilma-stub>
